### ISSUE TITLE
Packages for reproducing experiments

### ISSUE THREAD

**Issue by JELAshford** [Zhangyanbo/diffusion-evolution#1]
Hi! Thanks so much for providing this codebase. I'm trying to reproduce the "benchmarks" experiment by running `plotbenchmark.py`, but am running into issues with not knowing which packages/versions are needed. For example, I'm having trouble finding the correct `hades` package to run the `cmaes` benchmark file. 

A possible fix for this would be providing a `requirements.txt` or similar for each experiment - could this be arranged?

**Comment by Zhangyanbo** [comment]
Thank you for your comment! We are going to release these packages soon. And I'm also planning to extract the CMA-ES / PEPG / OpenES part from that package so you don't need any dependency.

**Comment by JELAshford** [comment]
Sounds good, looking forward to it!

**Comment by DK-cpy** [comment]
Hello, thank you very much for sharing your code, but I encountered the following problem while reproducing it: 
from foobench import Objective
ModuleNotFoundError: No module named 'foobench'

**Comment by Zhangyanbo** [comment]
Hi, you can find `foobench` here: https://github.com/bhartl/foobench

I guess you may also face the same problem as @JELAshford -- you need `hades` package. We are working on this to remove this dependence. But it will not be a problem if you only do experiments on Diffusion Evolution. `hades` is only used for traditional methods here.

**Comment by DK-cpy** [comment]
Thank you for your response. As you anticipated, I do indeed require the hades package.Looking forward to your further work.

**Comment by Zhangyanbo** [comment]
All `hades` dependency are removed. You should able to run the experiments without any problem. You may install `pip cma` or `gym` depend on which experiment you perform. I'm not adding these into requirements because they are not required to run Diffusion Evolution, only comparison experiments require them.
